language: python
python:
  - 2.7
install:
  - "pip install -r requirements.txt"
  - "pip install pytest pytest-cov pytest-sugar"
  - "pip install coveralls"
  - "pip install -e ."
script:
  - py.test --cov pypact --cov-report term-missing
after_success:
  - coveralls
