language: python

sudo: false

python:
#  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install tox-travis
  - pip install pytest-cov
  - pip install coveralls
  - pip install -e .

script: tox

after_success: coveralls
