version: '2.1'

services:

  py27:
    command: sh -c "find . -name '*.pyc' -delete && python setup.py test"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: '/environments/Dockerfilepy27'

  py33:
    command: sh -c "find . -name '*.pyc' -delete && python setup.py test"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: '/environments/Dockerfilepy33'

  py34:
    command: sh -c "find . -name '*.pyc' -delete && python setup.py test"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: '/environments/Dockerfilepy34'

  py35:
    command: sh -c "find . -name '*.pyc' -delete && python setup.py test"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: '/environments/Dockerfilepy35'

  py36:
    command: sh -c "find . -name '*.pyc' -delete && python setup.py test"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: '/environments/Dockerfilepy36'

  py37:
    command: sh -c "find . -name '*.pyc' -delete && python setup.py test"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: '/environments/Dockerfilepy37'

  py38:
    command: sh -c "find . -name '*.pyc' -delete && python setup.py test"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: '/environments/Dockerfilepy38'
